version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: haghighi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: haghighi_db
      MYSQL_USER: haghighi_user
      MYSQL_PASSWORD: haghighi_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./moc-old-data/migration.sql:/docker-entrypoint-initdb.d/01-migration.sql
      - ./moc-old-data/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - haghighi_network

volumes:
  mysql_data:

networks:
  haghighi_network:
    driver: bridge
