version: '3.8'

services:
  postgres:
    image: postgres:15.14
    container_name: haghighi_postgres
    environment:
      POSTGRES_DB: haghighi_db
      POSTGRES_USER: haghighi_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: haghighi_backend
    environment:
      DATABASE_URL: "postgresql://haghighi_user:mysecretpassword@postgres:5432/haghighi_db?schema=public"
      JWT_SECRET: simple-jwt-secret
      JWT_EXPIRES_IN: 7d
      API_BASE_URL: http://localhost:3000
      PORT: 3000
      NODE_ENV: development
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: "/app/uploads"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: npm run start:dev

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    container_name: haghighi_admin
    environment:
      REACT_APP_API_URL: http://localhost:3000
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./admin-panel:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: haghighi_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
    ports:
      - "3002:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
