#!/bin/bash

# Manual deployment instructions for Haghighi Platform
# Since SSH authentication is not set up, follow these steps manually

echo "🚀 Manual Deployment Instructions for Haghighi Platform"
echo "=================================================="
echo ""
echo "Since SSH authentication is not configured, please follow these steps:"
echo ""
echo "1. 📁 First, create a compressed archive of the project:"
echo "   tar -czf haghighi-project.tar.gz backend frontend admin-panel docker-compose.prod.yml production.env deploy-prod.sh"
echo ""
echo "2. 📤 Upload the archive to your server using any method:"
echo "   - Use SFTP client (FileZilla, WinSCP, etc.)"
echo "   - Use web-based file manager"
echo "   - Use cloud storage and download on server"
echo ""
echo "3. 🔧 On your server, run these commands:"
echo "   mkdir -p /opt/haghighi"
echo "   cd /opt/haghighi"
echo "   # Extract the uploaded archive"
echo "   tar -xzf haghighi-project.tar.gz"
echo "   chmod +x deploy-prod.sh"
echo ""
echo "4. 🐳 Install Docker and Docker Compose on server:"
echo "   curl -fsSL https://get.docker.com -o get-docker.sh"
echo "   sh get-docker.sh"
echo "   curl -L \"https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-\$(uname -s)-\$(uname -m)\" -o /usr/local/bin/docker-compose"
echo "   chmod +x /usr/local/bin/docker-compose"
echo ""
echo "5. 🚀 Run the deployment:"
echo "   ./deploy-prod.sh 185.231.112.84"
echo ""
echo "6. 🔗 Copy uploads directory to server:"
echo "   # Copy the uploads folder to /opt/haghighi/uploads on server"
echo ""
echo "Alternative: Use rsync with password authentication:"
echo "rsync -avz --progress -e 'ssh -o PreferredAuthentications=password' ./ root@185.231.112.84:/opt/haghighi/"
