#!/bin/bash

# Script to install and configure Nginx for Haghighi Platform
# Run this script on your Ubuntu server

set -e

echo "🚀 Starting Nginx installation and configuration..."

# Update system
echo "📦 Updating system packages..."
sudo apt update
sudo apt upgrade -y

# Install Nginx
echo "📦 Installing Nginx..."
sudo apt install nginx -y

# Create SSL placeholder files if they don't exist
echo "📝 Creating SSL placeholder files..."
sudo mkdir -p /etc/letsencrypt/live
sudo mkdir -p /etc/letsencrypt/archive

# Create options-ssl-nginx.conf if it doesn't exist
if [ ! -f /etc/letsencrypt/options-ssl-nginx.conf ]; then
    echo "📝 Creating /etc/letsencrypt/options-ssl-nginx.conf..."
    sudo tee /etc/letsencrypt/options-ssl-nginx.conf > /dev/null <<'EOF'
# This file will be updated by certbot
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
EOF
fi

# Create ssl-dhparams.pem if it doesn't exist
if [ ! -f /etc/letsencrypt/ssl-dhparams.pem ]; then
    echo "📝 Creating /etc/letsencrypt/ssl-dhparams.pem..."
    if command -v openssl &> /dev/null; then
        sudo openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048 2>/dev/null || {
            # If openssl fails, create a dummy file (will be replaced by certbot)
            sudo tee /etc/letsencrypt/ssl-dhparams.pem > /dev/null <<'EOF'
# This file will be generated by certbot
EOF
        }
    else
        # Create a dummy file if openssl is not available
        sudo tee /etc/letsencrypt/ssl-dhparams.pem > /dev/null <<'EOF'
# This file will be generated by certbot
EOF
    fi
fi

# Create placeholder SSL certificates directories for each domain
DOMAINS=("manehaghighi.com" "admin.manehaghighi.com" "api.manehaghighi.com" "mail.manehaghighi.com")
for domain in "${DOMAINS[@]}"; do
    if [ ! -d "/etc/letsencrypt/live/$domain" ]; then
        echo "📝 Creating placeholder directory for $domain..."
        sudo mkdir -p "/etc/letsencrypt/live/$domain"
        # Create dummy certificate files (will be replaced by certbot)
        sudo tee "/etc/letsencrypt/live/$domain/fullchain.pem" > /dev/null <<'EOF'
# Placeholder - will be replaced by certbot
EOF
        sudo tee "/etc/letsencrypt/live/$domain/privkey.pem" > /dev/null <<'EOF'
# Placeholder - will be replaced by certbot
EOF
        sudo chmod 600 "/etc/letsencrypt/live/$domain/privkey.pem"
    fi
done

# Enable Nginx (but don't start yet - we need to copy configs first)
echo "🔄 Enabling Nginx..."
sudo systemctl enable nginx

# Copy configuration files
echo "📝 Copying Nginx configuration files..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sudo cp "$SCRIPT_DIR/nginx/frontend.conf" /etc/nginx/sites-available/frontend.conf
sudo cp "$SCRIPT_DIR/nginx/admin.conf" /etc/nginx/sites-available/admin.conf
sudo cp "$SCRIPT_DIR/nginx/api.conf" /etc/nginx/sites-available/api.conf
sudo cp "$SCRIPT_DIR/nginx/mail.conf" /etc/nginx/sites-available/mail.conf

# Copy rate limiting configuration
if [ -f "$SCRIPT_DIR/nginx/rate-limiting.conf" ]; then
    echo "📝 Copying rate limiting configuration..."
    sudo mkdir -p /etc/nginx/conf.d
    sudo cp "$SCRIPT_DIR/nginx/rate-limiting.conf" /etc/nginx/conf.d/rate-limiting.conf
    
    # Check if nginx.conf includes conf.d directory
    if ! grep -q "include.*conf.d.*\.conf" /etc/nginx/nginx.conf; then
        echo "⚠️  Warning: nginx.conf doesn't include conf.d/*.conf"
        echo "   You may need to add 'include /etc/nginx/conf.d/*.conf;' to the http block in /etc/nginx/nginx.conf"
    fi
fi

# Create symbolic links
echo "🔗 Creating symbolic links..."
sudo ln -sf /etc/nginx/sites-available/frontend.conf /etc/nginx/sites-enabled/
sudo ln -sf /etc/nginx/sites-available/admin.conf /etc/nginx/sites-enabled/
sudo ln -sf /etc/nginx/sites-available/api.conf /etc/nginx/sites-enabled/
sudo ln -sf /etc/nginx/sites-available/mail.conf /etc/nginx/sites-enabled/

# Remove default Nginx site
if [ -f /etc/nginx/sites-enabled/default ]; then
    echo "🗑️  Removing default Nginx site..."
    sudo rm /etc/nginx/sites-enabled/default
fi

# Test Nginx configuration
echo "🧪 Testing Nginx configuration..."
if sudo nginx -t; then
    echo "✅ Nginx configuration is valid"
else
    echo "❌ Nginx configuration has errors"
    echo "⚠️  Note: SSL certificates are placeholders. Run certbot to get real certificates."
    exit 1
fi

# Start/Reload Nginx
echo "🔄 Starting/Reloading Nginx..."
if sudo systemctl is-active --quiet nginx; then
    sudo systemctl reload nginx
else
    sudo systemctl start nginx
fi

# Check Nginx status
if sudo systemctl is-active --quiet nginx; then
    echo "✅ Nginx is running"
else
    echo "❌ Nginx failed to start"
    exit 1
fi

echo "✅ Nginx installation and configuration completed!"
echo ""
echo "⚠️  IMPORTANT: Before accessing the sites, you need to:"
echo "   1. Configure DNS records for your domains"
echo "   2. Install SSL certificates with Certbot (run: sudo ./ssl/install-certbot.sh)"
echo "   3. Make sure Docker containers are running on ports 8080, 8081, and 8082"
echo ""
echo "Next steps:"
echo "   - Run: sudo ./ssl/install-certbot.sh"
